# Deploy Tusky Nightly on each push to develop

when:
  - event: push
    branch: develop

depends_on:
  - check-and-build

steps:
  # https://github.com/woodpecker-ci/woodpecker/issues/5181
  - name: fix permissions
    # using this image specifically because it runs as root, like the clone step also does
    image: woodpeckerci/plugin-git
    commands:
      - chmod -R 777 .

  - name: Deploy
    image: cimg/android:2025.09.1
    environment:
      KEYSTORE:
        from_secret: KEYSTORE
      KEY_ALIAS_TEST:
        from_secret: KEY_ALIAS_TEST
      KEY_PASSWORD_TEST:
        from_secret: KEY_PASSWORD_TEST
      KEYSTORE_PASSWORD:
        from_secret: KEYSTORE_PASSWORD
      ANDROID_PUBLISHER_CREDENTIALS:
        from_secret: ANDROID_PUBLISHER_CREDENTIALS
    commands:
      # create changelog file
      - mkdir -p app/src/greenRelease/play/release-notes/en-US
      - git log -3 --pretty=%B | head -c 500 > app/src/greenRelease/play/release-notes/en-US/default.txt
      # prepare keystore
      - echo $KEYSTORE | base64 -d > app/Tusky.jks
      # update versioncode relative to build number
      - export VERSION_CODE=$(( ${CI_PIPELINE_NUMBER} + 12000 ))
      - sed -i'.original' -e "s/^\([[:space:]]*versionCode[[:space:]]*\)[0-9]*/\\1$VERSION_CODE/" app/build.gradle
      # build and upload
      - export GRADLE_USER_HOME=$PWD/.gradle
      - ./gradlew app:bundleGreenRelease app:publishGreenReleaseBundle
